### PR TITLE
Try to fix the test

### PR DESCRIPTION
**Pull request by HenryLeongStat**
Seems like there is no `nullable` in feather read anymore.

### CODE REVIEW

**Review by BoPeng — COMMENTED** [review]
Did you test it?

**Comment by HenryLeongStat** [comment]
I tested couple variable types manually.

The current fail is caused by `isdefined()`. We can't do something like `isdefined(:module)` anymore. The updated julia isn't that friendly... I will take care of it when I have time...

**Comment by BoPeng** [comment]
Thanks. Let us merge this after all tests are fixed.

**Comment by HenryLeongStat** [comment]
I guess it will take a while... A lot of old functions are not working anymore!!! 💢

**Comment by BoPeng** [comment]
That is indeed a big 1.1 release. In theory everything should be kept backward compatible after 1.0 (and this is why I have stuck with sos 0.x.x for so long.

**Comment by HenryLeongStat** [comment]
Yes! And I couldn't find any document as well!! I fixed it by reading other repos' pushes.

**Pull request closed without merging**
